---
title: "SNUBH Sepsis"
subtitle: "w/ Korean Sepsis Alliance"
author: "S Y Lim"
format: 
  pptx:
    df-print: kable
---

```{r}
#| include: false

knitr::opts_chunk$set(echo=F)
library(ggplot2)
library(data.table)
library(ggthemes)
library(gtsummary)
library(ggsignif)

dt <- fread('../data/KSA2.csv')
dt_sepsis = copy(dt[Antibiot %between% c(0,600) &
                      Center %in% c("분당서울대학교병원",
                                  "삼성서울병원","서울대학교병원",
                                  "서울아산병원(내과계)","서울아산병원(외과계)")])

dt_sepsis[,sepsis_group := factor(fcase(Elig02==1,"Septic shock",
                                  Elig02==0,"Sepsis"), levels = c("Septic shock","Sepsis"))]

dt_sepsis[,Center_binary := fifelse(Center %like% "분당","SNUBH","Top 10%")]
dt_sepsis[,TypeOfInfection := ifelse(TypeInfection_MOSAICS==1,'Community','Hospital')]
sepsis_linetype = c("Overall"="solid",
                    "Septic shock"="dash",
                    "Sepsis"="dotted")
sepsis_linetype = factor(sepsis_linetype, levels = c("solid","dash","dotted"), ordered = T)

```

# Antibiotics

## TZ ~ Antibiotics: SNUBH vs Top 10
```{r}
antibiot_density = ggplot() +
  stat_density(
    data=dt_sepsis,
    geom="line",
    aes(x=Antibiot, lty = "Overall")
    ) +
  stat_density(
    data=dt_sepsis[sepsis_group == "Septic shock"],
    geom="line",
    aes(x=Antibiot, lty = "Septic shock")
  ) +
  stat_density(
    data=dt_sepsis[sepsis_group == "Sepsis"],
    geom="line",
    aes(x=Antibiot, lty = "Sepsis")
  ) + 
  scale_linetype_manual(values = sepsis_linetype,
                        breaks= c("Overall","Septic shock","Sepsis"))+
  scale_x_continuous(breaks=seq(0,600,50)) +
  theme_classic() +
  theme(legend.position = c(0.8,0.8),
        legend.title = element_blank(),
        legend.key.width = unit(3,"cm"),
        strip.background = element_blank(),
        strip.text = element_text(size=15, face="bold"))

antibiot_density + facet_grid(~Center_binary)
```

## TZ ~ Antibiotics: SNUBH vs Top 10
```{r}
tbl_strata(
  data=dt_sepsis,
  strata = Center_binary,
  .tbl_fun = ~.x |> 
    tbl_summary(by=sepsis_group,
                include = Antibiot,
                statistic = everything()~"{median} [{p25}-{p75}]") |> 
    add_overall() |> 
    add_p(),
  .combine_with = "tbl_merge",
) |> 
  modify_footnote(everything() ~ NA)
```

## TZ ~ Antibiotics: Community vs Hospital

```{r}
antibiot_density + facet_grid(~TypeOfInfection)

```

## TZ ~ Antibiotics: Community vs Hospital
```{r}
tbl_strata(
  data=dt_sepsis,
  strata = TypeOfInfection,
  .tbl_fun = ~.x |> 
    tbl_summary(by=sepsis_group,
                include = Antibiot,
                statistic = everything()~"{median} [{p25}-{p75}]") |> 
    add_overall() |> 
    add_p(),
  .combine_with = "tbl_merge",
) |> 
  modify_footnote(everything() ~ NA)
```

# Blood culture

## TZ ~ Blood culture: SNUBH vs Top 10%
```{r}
dt_blood = copy(dt[blood %between% c(0,100) &
                     Center %in% c("분당서울대학교병원",
                                   "삼성서울병원","서울대학교병원",
                                   "서울아산병원(내과계)","서울아산병원(외과계)")])
dt_blood[,Center_binary := fifelse(Center %like% "분당","SNUBH","Top 10%")]
dt_blood[,TypeOfInfection := ifelse(TypeInfection_MOSAICS==1,'Community','Hospital')]
dt_blood[,sepsis_group := factor(fcase(Elig02==1,"Septic shock",
                                        Elig02==0,"Sepsis"), levels = c("Septic shock","Sepsis"))]
blood_density = ggplot() +
  stat_density(
    data=dt_blood,
    geom="line",
    aes(x=blood, lty = "Overall")
  ) +
  stat_density(
    data=dt_blood[sepsis_group == "Septic shock"],
    geom="line",
    aes(x=blood, lty = "Septic shock")
  ) +
  stat_density(
    data=dt_blood[sepsis_group == "Sepsis"],
    geom="line",
    aes(x=blood, lty = "Sepsis")
  ) + 
  scale_linetype_manual(values = sepsis_linetype,
                        breaks= c("Overall","Septic shock","Sepsis"))+
  scale_x_continuous(breaks=seq(0,100,10)) +
  theme_classic() +
  theme(legend.position = c(0.85,0.8),
        legend.title = element_blank(),
        legend.key.width = unit(3,"cm"),
        strip.background = element_blank(),
        strip.text = element_text(size=15, face="bold"))
blood_density + facet_grid(~Center_binary)
```

## TZ ~ Blood culture: SNUBH vs Top 10%

```{r}
tbl_strata(
  data=dt_blood,
  strata = Center_binary,
  .tbl_fun = ~.x |> 
    tbl_summary(by=sepsis_group,
                include = blood,
                statistic = everything()~"{median} [{p25}-{p75}]") |> 
    add_overall(),
  .combine_with = "tbl_merge",
) |> 
  modify_footnote(everything() ~ NA)
```


# Bundle compliance

## Antibiotics 1~6h

```{r}
dt[,Center_binary := fifelse(Center %like% "분당","SNUBH","Top 10%")]
dt_bundle_anti_long = dt[,.(anti1h, anti3h, anti6h, Center_binary)] |> 
  melt(measure.vars = patterns("anti"))

anti = c("anti1h","anti3h", "anti6h")
anti_pval = sapply(anti, \(x)
                   dt_bundle_anti_long[variable==x, chisq.test(Center_binary,value)]$p.value
       )

anti_pval2 = ifelse(anti_pval < 0.001,"<.001",round(anti_pval,4))


# Figure
dt_bundle_anti_long[,.N,by=.(Center_binary, variable, value)][,prop := N/sum(N)*100, by=.(Center_binary, variable)][value==1] |> 
  ggplot(aes(x=variable, y=prop, fill= Center_binary)) +
  geom_col(position = position_dodge()) +
  scale_x_discrete(labels=c("1 Hour","3 Hour", "6 Hour")) + 
  scale_y_continuous(expand=c(0,0), limits=c(0,100)) + 
  scale_fill_few() +
  theme_classic() +
  labs(y="Antibiotics, %") +
  theme(legend.position = "top",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=15),
        axis.text= element_text(size=15),
        axis.ticks = element_blank(),
        legend.text = element_text(size=15,
                                   margin=margin(r=20)))+
  geom_signif(
    y_position = c(30, 75, 95),
    xmin = c(0.8, 1.8, 2.8), 
    xmax = c(1.2, 2.2, 3.2),
    annotations = anti_pval2,
    tip_length = 0
  ) +
  geom_text(
    aes(label=round(prop,1), y=prop),
    position = position_dodge(width=.9),
    vjust=1.5,
    size=5
  )

```


## Blood culture 1~6h

```{r}
dt_bundle_blood_culture_long = dt[,.(bd1h, bd3h, bd6h, Center_binary)] |> 
  melt(measure.vars = patterns("bd"))

bc = c("bd1h","bd3h","bd6h")
bc_pval = sapply(bc, \(x)
                 dt_bundle_blood_culture_long[variable==x, chisq.test(Center_binary,value)]$p.value
)
bc_pval2 = ifelse(bc_pval < 0.001,"<.001",round(bc_pval,4))

dt_bundle_blood_culture_long[,.N,by=.(Center_binary, variable, value)][,prop := N/sum(N)*100, by=.(Center_binary, variable)][value==1] |> 
  ggplot(aes(x=variable, y=prop, fill= Center_binary)) +
  geom_col(position = position_dodge()) +
  scale_x_discrete(labels=c("1 Hour","3 Hour", "6 Hour")) + 
  scale_y_continuous(expand=c(0,0), limits=c(0,100)) + 
  scale_fill_few() +
  theme_classic() +
  labs(x="Hospital", y="Blood culture, %") +
  theme(legend.position = "top",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=15),
        axis.text= element_text(size=15),
        axis.ticks = element_blank(),
        legend.text = element_text(size=15,
                                   margin=margin(r=20)))+
  geom_signif(
    y_position = c(75, 90, 96),
    xmin = c(0.8, 1.8, 2.8), 
    xmax = c(1.2, 2.2, 3.2),
    annotations = bc_pval2,
    tip_length = 0
  ) +
  geom_text(
    aes(label=round(prop,1), y=prop),
    position = position_dodge(width=.9),
    vjust=1.5,
    size=5
  )
```

